### ISSUE TITLE
not a issue

### ISSUE THREAD

**Issue by AnshhSingh** [Snowflake107/discord-player-extractors#3]
I wanted to ask how what are the different extractor supported and is the attachment links working? because I had some problems

**Comment by twlite** [comment]
This package supports `Vimeo`, `Facebook`, `Raw links` and `Reverbnation`

**Comment by twlite** [comment]
also, for `Attachment` to work, your link should be a raw link such as `cdn.discordapp.com`

**Comment by AnshhSingh** [comment]
okay thanks!
